# version: '3'
# services:
#   redis-server:
#     image: 'redis'
#   node-app:
#     restart: always
#     build: .
#     ports:
#       - '4001:8081'

version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
